# Generated by Django 3.2.4 on 2021-08-29 15:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import book.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'main_genre',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('published_year', models.PositiveIntegerField(
                    validators=[django.core.validators.MinValueValidator(1950), book.models.max_value_current_year],
                    verbose_name='Год публикации')),
                ('cover', models.ImageField(upload_to=book.models.get_timestamp_path, verbose_name='Обложка')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления на сайт')),
                ('authors', models.ManyToManyField(to='author.Author', verbose_name='Авторы')),
                ('genre',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-added_at'],
            },
        ),
    ]
