# Generated by Django 3.2.4 on 2021-08-29 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genre',
            table=None,
        ),
    ]
