# Generated by Django 3.2.4 on 2021-08-29 15:48

import django.core.validators
from django.db import migrations, models

import book.models


class Migration(migrations.Migration):
    dependencies = [
        ('book', '0002_alter_genre_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.PositiveIntegerField(default=book.models.current_year,
                                              validators=[django.core.validators.MinValueValidator(1900),
                                                          book.models.max_value_current_year],
                                              verbose_name='Год публикации'),
        ),
    ]
