# Generated by Django 3.2.4 on 2021-08-30 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('book', '0003_alter_book_published_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)],
                                              verbose_name='Рейтинг'),
        ),
    ]
